### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by YarUnderoaker** [Samson-Mano/2D_Heat_transfer#1]
Hi. There is impossible to compile this project because a files is missing: Program.cs, solver_form.cs, Useful_Function.cs

**Comment by Samson-Mano** [comment]
Hi

Thanks for the feedback.

I just noticed all the files are uploaded properly. I reuploaded the
missing files. Please give it a try. If you still face problems give me a
shout out.

Thanks
Samson Mano

**Comment by YarUnderoaker** [comment]
Thank you for quick response. Now all fine.
